services:
  coordinator:
    image: prestodb/presto:latest
    volumes:
      - ./conf/coordinator/config.properties:/opt/presto-server/etc/config.properties
      - ./conf/coordinator/jvm.config:/opt/presto-server/etc/jvm.config
      - ./catalog:/opt/presto-server/etc/catalog

    ports:
      - '8080:8080'

  worker-1:
    image: prestodb/presto:latest
    volumes:
      - ./conf/worker1/config.properties:/opt/presto-server/etc/config.properties
      - ./conf/worker1/jvm.config:/opt/presto-server/etc/jvm.config
      - ./catalog:/opt/presto-server/etc/catalog
    ports:
      - '8081:8081'

  worker-2:
    image: prestodb/presto:latest
    volumes:
      - ./conf/worker1/config.properties:/opt/presto-server/etc/config.properties
      - ./conf/worker1/jvm.config:/opt/presto-server/etc/jvm.config
      - ./catalog:/opt/presto-server/etc/catalog
    ports:
      - '8082:8082'

  presto-mongo:
    image: mongo:6.0.4
    volumes:
      - ./data/book.js:/docker-entrypoint-initdb.d/book.js
    
  
  presto-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: presto
    volumes:
      - ./data/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    
 
networks:
  presto_network:
    external: true